const actionTypes = {
  FETCHED_USER_DATA: 'FETCHED_USER_DATA',
  REQUESTED_USER_DATA: 'REQUESTED_USER_DATA',
  REQUESTED_USER_DATA_SUCCEEDED: 'REQUESTED_USER_DATA_SUCCEEDED',
  REQUESTED_USER_DATA_FAILED: 'REQUESTED_USER_DATA_FAILED',
}

export default actionTypes;