const actionTypes = {
  FETCHED_USER_DATA: 'FETCHED_USER_DATA',
  REQUESTED_USER_DATA: 'REQUESTED_USER_DATA',
  REQUESTED_USER_DATA_SUCCEEDED: 'REQUESTED_USER_DATA_SUCCEEDED',
  REQUESTED_USER_DATA_FAILED: 'REQUESTED_USER_DATA_FAILED',
  SET_EMOJI: 'SET_EMOJI',
  SET_COLOR: 'SET_COLOR',
}

export default actionTypes;